#!/usr/bin/expect -f

set timeout 300
set host [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set local_file [lindex $argv 3]
set remote_path [lindex $argv 4]

spawn scp -o StrictHostKeyChecking=no $local_file $user@$host:$remote_path

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    eof
}
